server.port=8081

# ===============================
# EUREKA
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ===============================
# POSTGRESQL
# ===============================
# Añadimos ?currentSchema=auth para que conecte directo a tu esquema
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db?currentSchema=auth
spring.datasource.username=auth_app
spring.datasource.password=AuthApp#2026
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
# Como ya creaste las tablas con el script, usa 'validate' o 'none' para evitar conflictos
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Obligamos a Hibernate a usar el esquema auth por defecto en las consultas
spring.jpa.properties.hibernate.default_schema=auth
# Esto es vital para que reconozca que usas PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT
# ===============================
jwt.secret=bXlfc3VwZXJfc2VjcmV0X2tleV8yMDI2X2F1dGhfc2VydmljZQ==
jwt.expiration=3600000

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

# =========================
# INFO
# =========================
info.app.name=auth-service
info.app.version=1.0.0
info.app.description=Authentication Microservice
info.app.author=D Machaca

# =========================
# RECAPCHA GOOGLE CONFIG
# =========================
recaptcha.siteKey=6LcV3tgsAAAAAMN20TXl9Jw1UttEtkru-p_Ppwzg
recaptcha.secretKey=6LcV3tgsAAAAAMJNVsu-FzJhobEcOQ1LVYcLdW9d
recaptcha.threshold=0.5
recaptcha.validar=false
seguridad.validar=true
recaptcha.url.template=https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s&remoteip=%s