# =========================================================
# CONFIGURACIÓN DEL MICROSERVICIO: CITA-SERVICE
# =========================================================
server.port=8084
spring.application.name=cita-service

# EUREKA CONFIG
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# DATABASE: POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cita_db?currentSchema=cita
spring.datasource.username=cita_app
spring.datasource.password=CitaApp#2026
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=cita
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# =========================================================
# CONFIGURACIÓN DE RESILIENCIA Y COMUNICACIÓN (CITA-SERVICE)
# =========================================================

# 1. HABILITAR CIRCUIT BREAKER
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.circuitbreaker.group.enabled=true

# 2. CONFIGURACIÓN DE TIMEOUTS (RED Y CIRCUIT BREAKER)
# Tiempo límite total de la operación antes de activar el Fallback
resilience4j.timelimiter.configs.default.timeout-duration=5s

# Timeouts específicos de Feign (Capa de red)
# connect-timeout: Tiempo para establecer la conexión inicial
feign.client.config.default.connect-timeout=5000
# read-timeout: Tiempo máximo de espera entre paquetes de datos
feign.client.config.default.read-timeout=5000

# 3. CONFIGURACIÓN DEL CIRCUIT BREAKER (RESILIENCE4J)
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.sliding-window-size=10
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s

# 4. VARIABLES DE URL PARA TUS CLIENTES FEIGN
# Se mantienen por si tu código Java las referencia con @Value
app.services.personal.url=http://personal-service
app.services.paciente.url=http://paciente-service

# 5. ESTRATEGIA DE SEGURIDAD Y CONTEXTO
# Hereda el JWT/SecurityContext a los hilos del Circuit Breaker
spring.security.strategy=MODE_INHERITABLETHREADLOCAL
spring.main.allow-bean-definition-overriding=true

# =========================================================
# MONITOREO (ACTUATOR)
# =========================================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true