server.port=8084

spring.application.name=cita-service

# ===============================
# EUREKA
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ===============================
# POSTGRESQL
# ===============================
# Añadimos ?currentSchema=auth para que conecte directo a tu esquema
spring.datasource.url=jdbc:postgresql://localhost:5432/cita_db?currentSchema=cita
spring.datasource.username=cita_app
spring.datasource.password=CitaApp#2026
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
# Como ya creaste las tablas con el script, usa 'validate' o 'none' para evitar conflictos
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Obligamos a Hibernate a usar el esquema auth por defecto en las consultas
spring.jpa.properties.hibernate.default_schema=cita
# Esto es vital para que reconozca que usas PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

