server.port=8761

spring.application.name=discovery-service

# ===============================
# EUREKA SERVER
# ===============================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# ===============================
# HOST
# ===============================
eureka.instance.hostname=localhost

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always