server.port=8080

# ===============================
# EUREKA
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ===============================
# GATEWAY ROUTES (VERSIÓN MODERNA)
# ===============================

# AUTH SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/v1/api/auth/**

# PACIENTE SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=paciente-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PACIENTE-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/v1/api/pacientes/**

# PERSONAL SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=personal-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PERSONAL-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/v1/api/personal/**

# CITA SERVICE
spring.cloud.gateway.server.webflux.routes[3].id=cita-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://CITA-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/v1/api/cita/**

# ATENCION SERVICE
spring.cloud.gateway.server.webflux.routes[4].id=atencion-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://ATENCION-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/v1/api/atenciones/**

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

# ===============================
# JWT
# ===============================
application.security.jwt.secret=bXlfc3VwZXJfc2VjcmV0X2tleV8yMDI2X2F1dGhfc2VydmljZQ==
